### ISSUE TITLE
Wrong codepoints for superscripts 

### ISSUE THREAD

**Issue by rengel-de** [kipcole9/calendrical#4]
Module `Calendrical.Math.Fraction` in file `math.ex`.
From the `@doc` of function `to_string`:

```
  ## Example
      iex> Calendrical.Math.Fraction.to_string {2, {16, 25}}
      "2ⁱ⁶⁄₂₅"
```

The numerator contains the character "i" instead of "1".
The codepoint for digit "3" is missing. 
These changes of function `superscript` help:

```
@spec superscript(integer) :: String.t
- def superscript(digit) when digit in [0,1,4,5,6,7,8,9] do   # always catches digit '1'
+ def superscript(digit) when digit in [0,4,5,6,7,8,9] do     # `1` deleted
    <<226, 129, 176 + digit>>
  end
- def superscript(1), do: "\u2071"    # this produces character "ⁱ" instead of digit "¹"
+ def superscript(1), do: "\u00b9"    # correct codepoint
  def superscript(2), do: "\u00b2"
+ def superscript(3), do: "\u00b3"    # additional codepoint
```

**Comment by kipcole9** [comment]
@rengel-de Thanks much for this, and the other issues.  I've finished up the current work on another project and will be back into Calendrical from now.

I'm thinking to:

* Just focus on Gregorian and ISOWeek calendars for now; 
* stabilise the API,
* improve the code and implement additional testing,
* move the "ancient calendars" to their own library

Does that cause you any negative issues on the work you're doing?

**Comment by rengel-de** [comment]
@kipcole9 
> Does that cause you any negative issues on the work you're doing?

No, not at all. I'm new to Elixir and just finished the course 'Elixir for Programmers' by Dave Thomas (https://codestool.coding-gnome.com/courses/elixir-for-programmers). My main interest are timelines 
(https://github.com/rengel-de/timeline). In the past, I've used parts of Calendrical in JavaScript and Python (pycalcal) to do various date-time conversions. Now, that I'm learning Elixir, I study your 'calendrical' to get a feeling how things are done in Elixir. 

In his course, Dave Thomas repeatedly stressed and demonstrated the application of the SRP (Single Responsibility Principle) for the development of functions and complete modules. If possible, he even breaks up a single project (in his course a version of Hangman) into separate smaller standalone subprojects and recombines them using the 'deps' in 'mix.exs'. 

As you know, the Common Lisp and Python versions of Calendrical are monolithic monsters that are hardly manageable. Inspired by Dave Thomas, I try to find parts of Calendrical that might be suitable for the application of the SRP. For this, your Elixir version is quite helpful. Right now, these are just exercises to get my feet wet with Elixir. 

My very first excercise was a small module called 'FractionFormatter', refactored from your 'math.ex'. That's how I found this superscript issue. In case, you might be interested, I've included the result as zip file [fraction_formatter.zip](https://github.com/kipcole9/calendrical/files/1671003/fraction_formatter.zip).

In the past, I've written a small JavaScript application called c3 (calendar cross converter). It can be run in a browser and might help you cross-checking Gregorian and ISOWeek calendars 
[c3.zip](https://github.com/kipcole9/calendrical/files/1671021/c3.zip).

**Comment by kipcole9** [comment]
Thanks for the feedback and pointers.  In my [Cldr](https://github.com/kipcole9/cldr) I started out monolithic but quickly realised that not every app needs all parts and so split it out now into about 6 dependent packages.  Elixir's package manager, Hex, makes it really easy to manage the dependencies.

I'll be cracking on with Calendrical this week.  I plan to use it remove some duplicate code in [cldr_dates_times](https://github.com/kipcole9/cldr_dates_times).  Then its on to recurring events.
